# Generated by Django 5.0 on 2023-12-31 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vhsapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='is_selected',
            field=models.BooleanField(default=True),
        ),
    ]
